/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        'surface-container-lowest': '#030e20',
        'secondary-fixed': '#d7e3ff',
        'on-primary': '#002780',
        'on-primary-fixed-variant': '#0039b4',
        'secondary-container': '#22467e',
        'on-error': '#690005',
        'outline-variant': '#434655',
        'surface-container-high': '#1f2a3d',
        'on-background': '#d8e3fc',
        'inverse-primary': '#1e51db',
        'on-secondary-container': '#95b6f4',
        'on-tertiary-fixed-variant': '#003cad',
        'outline': '#8e90a0',
        'surface-bright': '#2f394d',
        'on-primary-fixed': '#001551',
        'surface-variant': '#2a3549',
        'on-surface': '#d8e3fc',
        'error': '#ffb4ab',
        'on-surface-variant': '#c4c5d7',
        'on-secondary': '#002f65',
        'surface-tint': '#b7c4ff',
        'on-tertiary': '#00287c',
        'surface-container-low': '#101c2e',
        'surface-dim': '#081326',
        'primary': '#2e5ce6',
        'primary-fixed': '#dce1ff',
        'on-secondary-fixed': '#001b3f',
        'error-container': '#93000a',
        'tertiary': '#b5c4ff',
        'surface-container-highest': '#2a3549',
        'inverse-on-surface': '#263144',
        'tertiary-fixed': '#dce1ff',
        'primary-fixed-dim': '#b7c4ff',
        'on-primary-container': '#e5e7ff',
        'secondary': '#abc7ff',
        'surface-container': '#152032',
        'on-tertiary-container': '#e5e8ff',
        'inverse-surface': '#d8e3fc',
        'secondary-fixed-dim': '#abc7ff',
        'surface': '#081326',
        'on-secondary-fixed-variant': '#22467e',
        'tertiary-fixed-dim': '#b5c4ff',
        'tertiary-container': '#2a5ee3',
        'background': '#081326',
        'on-tertiary-fixed': '#00164e',
        'primary-container': '#2e5ce6',
        'on-error-container': '#ffdad6'
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      }
    },
  },
  plugins: [],
}
